language: haskell
notifications:
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313vector-space-points\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
